"""AURA v3 Kanonische Quant-Engine (aura.core).

Reine, deterministische Berechnungen ohne DOM-Abhaengigkeit.
Dokumentiert in docs/FORMULA_SPEC.md.
"""

from aura.core.indicators import (
    AdxResult,
    CvdResult,
    MacdResult,
    PivotPoint,
    PivotResult,
    SqueezeMetrics,
    SuperTrendResult,
    adx_series,
    atr_series,
    clamp,
    cvd_series,
    ema_series,
    macd_series,
    obv_series,
    rsi_series,
    sma_series,
    squeeze_metrics_at,
    stoch_rsi_series,
    supertrend_series,
    swing_pivots,
    vwap_series,
)
from aura.core.risk import (
    KellyResult,
    LeverageRecommendation,
    PositionSize,
    calc_kelly,
    recommend_leverage,
    size_position,
)
from aura.core.scoring import (
    LONG_TH,
    MACRO_CAP,
    MTF_NEED,
    SHORT_TH,
    W_BASIS,
    W_FUNDING,
    W_MOM,
    W_OI,
    W_STR,
    W_TREND,
    WARMUP_DEFAULT,
    AnalysisResult,
    BasisBias,
    DynamicTp1,
    FundingBias,
    FvgZone,
    LastBarSummary,
    MacroAdjustment,
    OpenInterestBias,
    RegimeInfo,
    aggregate_confluence_score,
    analyze_candles,
    calc_basis_bias,
    calc_funding_bias,
    calc_oi_bias,
    dynamic_tp1_at,
    macro_adjust,
    regime_of,
)
from aura.core.stats import (
    AccountingReconciliation,
    DsrResult,
    FoldGeometry,
    TradeEvaluation,
    calc_dsr,
    calibrate_probabilities,
    evaluate_trades,
    norm_cdf,
    norm_inv,
    reconcile_accounting,
    selection_objective,
    walk_forward_folds,
)

__all__ = [
    # Indikatoren
    "clamp",
    "ema_series",
    "sma_series",
    "rsi_series",
    "atr_series",
    "adx_series",
    "macd_series",
    "stoch_rsi_series",
    "supertrend_series",
    "obv_series",
    "vwap_series",
    "cvd_series",
    "swing_pivots",
    "squeeze_metrics_at",
    "AdxResult",
    "MacdResult",
    "SuperTrendResult",
    "CvdResult",
    "PivotResult",
    "PivotPoint",
    "SqueezeMetrics",
    # Scoring
    "W_TREND",
    "W_MOM",
    "W_VOL",
    "W_STR",
    "W_FUNDING",
    "W_OI",
    "W_BASIS",
    "MACRO_CAP",
    "LONG_TH",
    "SHORT_TH",
    "MTF_NEED",
    "WARMUP_DEFAULT",
    "aggregate_confluence_score",
    "analyze_candles",
    "regime_of",
    "dynamic_tp1_at",
    "macro_adjust",
    "calc_funding_bias",
    "calc_oi_bias",
    "calc_basis_bias",
    "AnalysisResult",
    "FvgZone",
    "LastBarSummary",
    "RegimeInfo",
    "DynamicTp1",
    "MacroAdjustment",
    "FundingBias",
    "OpenInterestBias",
    "BasisBias",
    # Risk
    "calc_kelly",
    "size_position",
    "recommend_leverage",
    "KellyResult",
    "PositionSize",
    "LeverageRecommendation",
    # Stats
    "norm_cdf",
    "norm_inv",
    "calc_dsr",
    "calibrate_probabilities",
    "evaluate_trades",
    "reconcile_accounting",
    "walk_forward_folds",
    "selection_objective",
    "DsrResult",
    "TradeEvaluation",
    "AccountingReconciliation",
    "FoldGeometry",
]
